#pragma once

void mp3_oled_controller_icons__print_left_nav(bool is_on_player_screen);
void mp3_oled_controller_icons__print_right_nav(bool is_on_player_screen);
void mp3_oled_controller_icons__print_play_icon(void);
void mp3_oled_controller_icons__print_pause_icon(void);
void mp3_oled_controller_icons__print_next_song_icon(void);